{% snapshot T_C1_SAT_PART%}
{{
config(
target_database='SDG_DV_TEST',
target_schema='SDG_DV_STG',
unique_key='ID_PART',

strategy='timestamp',
updated_at='TS_LOADED_AT',
)
}}

SELECT HASH(P_PARTKEY) AS ID_PART,
P_NAME AS ST_PART_NAME,
P_MFGR AS ST_PART_MFGR,
P_BRAND AS ST_PART_BRAND,
P_TYPE AS ST_PART_TYPE,
P_SIZE AS NU_PART_SIZE,
P_CONTAINER AS ST_PART_CONTAINER,
P_RETAILPRICE AS AM_PART_RETAILPRICE,
P_COMMENT AS LT_PART_COMMENT,
'SDG_DV_TEST_INGEST.PART' AS ST_SOURCE_FROM,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT
FROM {{ref('DS.PART')}}
{% endsnapshot %}
