{% snapshot T_C1_SAT_PARTSUPP%}
{{
config(
target_database='SDG_DV_TEST',
target_schema='SDG_DV_STG',
unique_key='ID_PARTSUPP',

strategy='timestamp',
updated_at='TS_LOADED_AT',
)
}}

SELECT HASH(PS_SUPPKEY || '-' || PS_PARTKEY) AS ID_PARTSUPP,
PS_AVAILQTY AS NU_PS_AVAILQTY,
PS_SUPPLYCOST AS AM_PS_SUPPLYCOST,
PS_COMMENT AS LT_PS_COMMENT,
'SDG_DV_TEST_INGEST.PARTSUPP' AS ST_SOURCE_FROM,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT
FROM {{ref('PARTSUPP')}}
{% endsnapshot %}
