{% snapshot T_C1_SAT_LINEITEM%}
{{
config(
target_database='SDG_DV_TEST',
target_schema='SDG_DV_STG',
unique_key='ID_LINEITEM',

strategy='timestamp',
updated_at='TS_LOADED_AT',
)
}}

SELECT HASH(L_ORDERKEY || '-' || L_PARTKEY || '-' || L_SUPPKEY || '-' || L_LINENUMBER) AS ID_LINEITEM,
L_QUANTITY AS NU_L_QUANTITY,
L_EXTENDEDPRICE AS AM_L_EXTENDEDPRICE,
L_DISCOUNT AS NU_L_DISCOUNT,
L_TAX AS NU_L_TAX,
L_RETURNFLAG AS ST_L_RETURNFLAG,
L_LINESTATUS AS ST_L_LINESTATUS,
L_SHIPDATE AS DT_L_SHIPDATE,
L_COMMITDATE AS DT_L_COMMITDATE,
L_RECEIPTDATE AS DT_L_RECEIPT,
L_SHIPINSTRUCT AS ST_L_SHIPINSTRUCT,
L_SHIPMODE AS ST_L_SHIPMODE,
L_COMMENT AS LT_L_COMMENT,
'SDG_DV_TEST_INGEST.LINEITEM' AS ST_SOURCE_FROM,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT
FROM {{ref('DS.LINEITEM')}}
{% endsnapshot %}
