{% snapshot T_C1_SAT_SUPPLIER%}
{{
config(
target_database='SDG_DV_TEST',
target_schema='SDG_DV_STG',
unique_key='ID_SUPPLIER',

strategy='timestamp',
updated_at='TS_LOADED_AT',
)
}}

SELECT HASH(S_SUPPKEY) AS ID_SUPPLIER,
S_NAME AS ST_SUP_NAME,
S_ADDRESS AS ST_SUP_ADRESS,
S_PHONE AS ST_SUP_PHONE,
S_ACCTBAL AS AM_SUP_ACCTBAL,
S_COMMENT AS LT_SUP_COMMENT,
'SDG_DV_TEST_INGEST.SUPPLIER' AS ST_SOURCE_FROM,
CURRENT_TIMESTAMP AS TS_LOADED_AT
FROM SDG_DV_TEST_INGEST.SUPPLIER
{% endsnapshot %}
