{% snapshot T_C1_LIK_PARTSUPP%}
{{
config(
target_database='SDG_DV_TEST',
target_schema='SDG_DV_STG',
unique_key='ID_SUPP_PART_SUPP',

strategy='timestamp',
updated_at='TS_LOADED_AT',
)
}}

SELECT HASH(PS_SUPPKEY || '-' || PS_PARTKEY) AS ID_SUPP_PART_SUPP,
HASH(PS_SUPPKEY) AS ID_SUPPLIER,
HASH(PS_PARTKEY) AS ID_PARTSUPP,
'SDG_DV_TEST_INGEST.PARTSUPP' AS ST_SOURCE_FROM,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT
FROM {{ref('DS.PARTSUPP')}}
{% endsnapshot %}
