{% snapshot T_C1_SAT_PARTSUPP%}
{{
config(
target_database='SDG_DV_TEST',
target_schema='SDG_DV_STG',
unique_key='ID_PARTSUPP',

strategy='timestamp',
updated_at='TS_LOADED_AT',
)
}}

SELECT HASH(PS_PARTKEY) AS ID_PARTSUPP,
PS_AVAILQTY AS NU_PS_AVAILQTY,
PS_SUPPLYCOST AS AM_PS_SUPPLYCOST,
PS_COMMENT AS LT_PS_COMMENT,
'SDG_DV_TEST_INGEST.PARTSUPP' AS ST_SOURCE_FROM,
CURRENT_TIMESTAMP AS TS_LOADED_AT
FROM SDG_DV_TEST_INGEST.PARTSUPP
{% endsnapshot %}
