{{ config(materialized='table',schema='SDG_DV_C2') }}

SELECT 
ID_CUSTOMER, 
TOTAL_AMOUNT, 
YEAR, 
'MET_TOTAL_AMOUNT_CUSTOMER' AS ST_SOURCE_FROM,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT 
FROM {{ref('TMP_TOTALS_ORDER')}}