{{ config(
    materialized='incremental',
    schema='SDG_DV_C2',
    pre_hook=[
      "UPDATE {{ this }} SET STATUS='UPD' || CURRENT_TIMESTAMP WHERE TS_LOADED_AT=(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AND STATUS='OK'"
    ]
    ) }}
SELECT  
ID_CUSTOMER,
CASE 
WHEN TOTAL_ORDERS < 3 THEN 'TCO_1'
WHEN TOTAL_ORDERS BETWEEN 3 AND 5 THEN 'TCO_2'
WHEN TOTAL_ORDERS BETWEEN 5 AND 8 THEN 'TCO_3'
WHEN TOTAL_ORDERS > 8  THEN 'TCO_4' END AS TP_CUST_ORDERS,
YEAR, 
'T_C2_SAT_TP_CUST_ORDERS' AS ST_SOURCE_FROM,
'OK'::VARCHAR(50) AS STATUS,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT
FROM {{ref('T_C2_SAT_TOTAL_ORDERS')}} A
WHERE 
A.STATUS='OK'
 