{{ config(
    materialized='incremental',
    schema='SDG_DV_C2',
    pre_hook=[
      "UPDATE {{ this }} SET STATUS='UPD' || CURRENT_TIMESTAMP WHERE TS_LOADED_AT=(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AND STATUS='OK'"
    ]
    ) }}
SELECT  
ID_CUSTOMER,
CASE 
WHEN TOTAL_PRODUCTS <= 200 THEN 'TCP_1'
WHEN TOTAL_PRODUCTS BETWEEN 200 AND 500 THEN 'TCP_2'
WHEN TOTAL_PRODUCTS BETWEEN 500 AND 800 THEN 'TCP_3'
WHEN TOTAL_PRODUCTS >= 1000  THEN 'TCP_4' 
ELSE 'TPC_5' END AS TP_CUST_PRODUCTS,
YEAR, 
'T_C2_SAT_TP_CUST_PRODUCTS' AS ST_SOURCE_FROM,
'OK'::VARCHAR(50) AS STATUS,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT
FROM {{ref('T_C2_SAT_TOTAL_PRODUCTS')}} A
WHERE 
A.STATUS='OK'





