{{ config(
    materialized='incremental',
    schema='SDG_DV_C2',
    pre_hook=[
      "UPDATE {{ this }} SET STATUS='UPD' || CURRENT_TIMESTAMP WHERE TS_LOADED_AT=(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AND STATUS='OK'"
    ]
    ) }}
SELECT  
ID_CUSTOMER,
CASE 
WHEN TOTAL_AMOUNT < 300000 THEN 'TCA_1'
WHEN TOTAL_AMOUNT BETWEEN 300000 AND 600000 THEN 'TCA_2'
WHEN TOTAL_AMOUNT BETWEEN 600000 AND 900000 THEN 'TCA_3'
WHEN TOTAL_AMOUNT > 900000  THEN 'TCA_4' END AS TP_CUST_AMOUNT,
YEAR, 
'T_C2_SAT_TP_CUST_AMOUNT' AS ST_SOURCE_FROM,
'OK'::VARCHAR(50) AS STATUS,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT
FROM {{ref('T_C2_SAT_TOTAL_AMOUNT')}} A
WHERE 
A.STATUS='OK'

