{{ config(materialized='table',schema='SDG_DV_C2') }}

SELECT B.ID_CUSTOMER, SUM(A.AM_ORD_TOTALPRICE) AS TOTAL_AMOUNT,COUNT(1) AS TOTAL_ORDERS, YEAR(A.DT_ORD_DATE) AS YEAR
FROM {{ref('T_C1_SAT_ORDERS')}} A
INNER JOIN {{ref('T_C1_LIK_CUST_ORDERS')}} B ON A.ID_ORDER = B.ID_ORDER
WHERE A.DBT_VALID_TO IS NULL AND B.DBT_VALID_TO IS NULL
GROUP BY B.ID_CUSTOMER, YEAR(A.DT_ORD_DATE) 
ORDER BY YEAR DESC, TOTAL_AMOUNT DESC

