{{ config(
    materialized='incremental',
    schema='SDG_DV_C2',
    pre_hook=[
      "UPDATE {{ this }} SET STATUS='UPD' || CURRENT_TIMESTAMP WHERE TS_LOADED_AT=(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AND STATUS='OK'"
    ]
    ) }}

SELECT
D.ID_CUSTOMER,
SUM(A.NU_L_QUANTITY) AS TOTAL_PRODUCTS,
YEAR(DT_ORD_DATE) AS YEAR, 
'T_C2_SAT_TOTAL_PRODUCTS' AS ST_SOURCE_FROM,
'OK'::VARCHAR(50) AS STATUS,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT 
FROM {{ref('T_C1_SAT_LINEITEM')}} A 
INNER JOIN {{ref('T_C1_LIK_LINEITEM')}} B ON A.ID_LINEITEM = B.ID_LINEITEM
INNER JOIN {{ref('T_C1_SAT_ORDERS')}} C ON B.ID_ORDER = C.ID_ORDER 
INNER JOIN {{ref('T_C1_LIK_CUST_ORDERS')}} D ON C.ID_ORDER = D.ID_ORDER 
WHERE 
A.DBT_VALID_TO IS NULL
AND B.DBT_VALID_TO IS NULL
AND C.DBT_VALID_TO IS NULL
GROUP BY
D.ID_CUSTOMER, YEAR(DT_ORD_DATE)




