{{ config(
    materialized='incremental',
    schema='SDG_DV_C2',
    pre_hook=[
      "UPDATE {{ this }} SET STATUS='UPD' || CURRENT_TIMESTAMP WHERE TS_LOADED_AT=(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AND STATUS='OK'"
    ]
    ) }}
SELECT 
ID_CUSTOMER, 
TOTAL_AMOUNT, 
YEAR, 
'MET_TOTAL_AMOUNT_CUSTOMER' AS ST_SOURCE_FROM,
'OK'::VARCHAR(50) AS STATUS,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT 
FROM {{ref('T_C2_TMP_TOTALS_ORDERS')}}
