SELECT 
AUX.YEAR,
CO_CUSTOMER AS CUSTOMER_CODE, 
ST_CUST_NAME AS CUSTOMER_NAME, 
ST_CUST_PHONE AS CUSTOMER_PHONE, 
ST_CUST_ADDRESS AS CUSTOMER_ADDRESS, 
ST_CUST_MKT_SEGMENT AS CUSTOMER_MARKET_SEGMENT,
TOTAL_PRODUCTS AS TOTAL_PRODUCTS_PURCHASED
FROM {{ref('T_C1_SAT_CUSTOMER')}} A
INNER JOIN {{ref('T_C1_HUB_CUSTOMER')}} B ON A.ID_CUSTOMER = B.ID_CUSTOMER
INNER JOIN {{ref('T_C3_DIM_YEARS')}} AUX ON 1=1
LEFT JOIN {{ref('T_C2_SAT_TOTAL_PRODUCTS')}} C ON A.ID_CUSTOMER = C.ID_CUSTOMER AND C.YEAR = AUX.YEAR
WHERE
A.DBT_VALID_TO IS NULL
AND B.DBT_VALID_TO IS NULL
AND C.STATUS = 'OK'