{{ config(
    materialized='incremental',
    schema='SDG_DV_C3',
    ) }}
SELECT 
AUX.YEAR,
CO_CUSTOMER AS CUSTOMER_CODE, 
ST_CUST_NAME AS CUSTOMER_NAME, 
ST_CUST_PHONE AS CUSTOMER_PHONE, 
ST_CUST_ADDRESS AS CUSTOMER_ADDRESS, 
ST_CUST_MKT_SEGMENT AS CUSTOMER_MARKET_SEGMENT,
TOTAL_ORDERS AS TOTAL_ORDERS,
TOTAL_PRODUCTS AS TOTAL_PRODUCTS_PURCHASED,
TOTAL_AMOUNT AS TOTAL_AMOUNT,
TP_CUST_ORDERS AS CUSTOMER_TYPE_BY_ORDERS,
TP_CUST_PRODUCTS AS CUSTOMER_TYPE_BY_PRODUCTS,
TP_CUST_AMOUNT AS CUSTOMER_TYPE_BY_AMOUNT, 
'T_C3_FAC_CUSTOMER' AS ST_SOURCE_FROM,
(SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP) AS TS_LOADED_AT,
(SELECT NVL(MAX(NU_VERSION),1)+1 FROM {{ this }} WHERE TS_LOADED_AT IN (SELECT TS_RUN FROM SDG_DV_TEST.SDG_DV_UTILS.T_UTILS_BATCH_TIMESTAMP))  AS NU_VERSION 
FROM {{ref('T_C1_SAT_CUSTOMER')}} A
INNER JOIN {{ref('T_C1_HUB_CUSTOMER')}} B ON A.ID_CUSTOMER = B.ID_CUSTOMER AND B.DBT_VALID_TO IS NULL
INNER JOIN {{ref('T_C3_TMP_YEARS')}} AUX ON 1=1
LEFT JOIN {{ref('T_C2_SAT_TOTAL_PRODUCTS')}} C ON A.ID_CUSTOMER = C.ID_CUSTOMER AND C.YEAR = AUX.YEAR AND C.STATUS = 'OK'
LEFT JOIN {{ref('T_C2_SAT_TOTAL_ORDERS')}} D ON A.ID_CUSTOMER = D.ID_CUSTOMER AND D.YEAR = AUX.YEAR AND D.STATUS = 'OK'
LEFT JOIN {{ref('T_C2_SAT_TOTAL_AMOUNT')}} E ON A.ID_CUSTOMER = E.ID_CUSTOMER AND E.YEAR = AUX.YEAR AND E.STATUS = 'OK'
LEFT JOIN {{ref('T_C2_SAT_TP_CUST_ORDERS')}} F ON A.ID_CUSTOMER = F.ID_CUSTOMER AND F.YEAR = AUX.YEAR AND F.STATUS = 'OK'
LEFT JOIN {{ref('T_C2_SAT_TP_CUST_PRODUCTS')}} G ON A.ID_CUSTOMER = G.ID_CUSTOMER AND G.YEAR = AUX.YEAR AND G.STATUS = 'OK'
LEFT JOIN {{ref('T_C2_SAT_TP_CUST_AMOUNT')}} H ON A.ID_CUSTOMER = H.ID_CUSTOMER AND H.YEAR = AUX.YEAR AND H.STATUS = 'OK'
WHERE
A.DBT_VALID_TO IS NULL

